services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  backend_tests:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["pytest", "backend/tests/test_backend.py"]
    environment:
      - FLASK_ENV=test
      - APP_ROLE=backend
    networks:
      - app-network

  frontend_tests:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: ["pytest", "frontend/tests/test_frontend.py"]
    environment:
      - FLASK_ENV=test
      - APP_ROLE=frontend
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge